Update main.py
Sorry, i'm new to the github, but It should be round bracket because square brackets lead to TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'